name: Deploy container to Azure Container Instances

on:
  workflow_call:
    inputs:
      DEPLOY_ENV:
        description: The environment to deploy to
        required: true
        type: string

      IMAGE_NAME:
        description: The name of the image to deploy
        required: true
        type: string

jobs:
  deploy-container:
    runs-on: ubuntu-latest
    
    environment: ${{ inputs.DEPLOY_ENV }}
    
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Log in to Azure using OIDC
      uses: azure/login@v2
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}

    - name: Deploy to Azure Container Instances
      uses: azure/aci-deploy@v1
      with:
        resource-group: ${{ github.event.repository.name }}-${{ inputs.DEPLOY_ENV }}
        dns-name-label: ${{ github.event.repository.name }}-${{ inputs.DEPLOY_ENV }}
        name: ${{ github.event.repository.name }}-container-${{ inputs.DEPLOY_ENV }}
        image: ${{ inputs.IMAGE_NAME }}:latest
        registry-login-server: ghcr.io
        registry-username: ${{ github.actor }}
        registry-password: ${{ secrets.GITHUB_TOKEN }}
        location: 'West Europe'
