name: Deploy container to Azure Container Instances

on:
  workflow_call:
    inputs:
      project_type:
        description: The environment to deploy to
        required: true
        type: string

      deploy_env:
        description: The environment to deploy to
        required: true
        type: string

      image_path:
        description: The path of the image to deploy
        required: true
        type: string

jobs:
  deploy-aci:
    if: ${{ inputs.project_type == 'ACI' }}
    runs-on: ubuntu-latest
    
    environment: ${{ inputs.deploy_env }}
    
    permissions:
      id-token: write
      contents: read
      packages: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Log in to the container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to Azure using OIDC
      uses: azure/login@v2
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}

    - name: Pull Docker image from registry
      env:
        IMAGE_PATH: ${{ inputs.image_path }}
      run: |
        echo "Pulling image $IMAGE_PATH from registry"
        docker pull $IMAGE_PATH

    - name: Deploy to Azure Container Instances
      uses: azure/aci-deploy@v1
      with:
        resource-group: ${{ github.event.repository.name }}-${{ inputs.deploy_env }}
        dns-name-label: ${{ github.event.repository.name }}-${{ inputs.deploy_env }}
        name: ${{ github.event.repository.name }}-container-${{ inputs.deploy_env }}
        image: ${{ inputs.image_path }}
        registry-login-server: ghcr.io
        registry-username: ${{ github.actor }}
        registry-password: ${{ secrets.GITHUB_TOKEN }}
        location: 'West Europe'
        ports: 443
