name: Deploy container to Azure Container Instances

on:
  workflow_call:
    inputs:
      DEPLOY_ENV:
        description: The environment to deploy to
        required: true
        type: string

      IMAGE_PATH:
        description: The path of the image to deploy
        required: true
        type: string

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  deploy-container:
    runs-on: ubuntu-latest
    
    environment: ${{ inputs.DEPLOY_ENV }}
    
    permissions:
      id-token: write
      contents: read
      packages: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Log in to the container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to Azure using OIDC
      uses: azure/login@v2
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}

    - name: Pull Docker image from registry
      env:
        IMAGE_PATH: ${{ inputs.IMAGE_PATH }}
      run: |
        echo "Pulling image $IMAGE_PATH from registry"
        docker pull $IMAGE_PATH

    - name: Deploy to Azure Container Instances
      uses: azure/aci-deploy@v1
      with:
        resource-group: ${{ github.event.repository.name }}-${{ inputs.DEPLOY_ENV }}
        dns-name-label: ${{ github.event.repository.name }}-${{ inputs.DEPLOY_ENV }}
        name: ${{ github.event.repository.name }}-container-${{ inputs.DEPLOY_ENV }}
        image: ${{ inputs.IMAGE_PATH }}
        registry-login-server: ${{ env.DOCKER_REGISTRY }}
        registry-username: ${{ github.actor }}
        registry-password: ${{ secrets.GITHUB_TOKEN }}
        location: 'West Europe'
