name: Deploy container to Azure Container Instances

on:
  workflow_call:
    inputs:
      DEPLOY_ENV:
        description: The environment to deploy to
        required: true
        type: string

      IMAGE_NAME:
        description: The name of the image to deploy
        required: true
        type: string

jobs:
  deploy-container:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Log in to Azure using OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Azure Container Instances
      uses: azure/aci-deploy@v1
      with:
        resource-group: ${{ github.event.repository.name }}-${{ inputs.DEPLOY_ENV }}
        dns-name-label: api.lerpz.com
        image: ${{ inputs.IMAGE_NAME }}
        name: ${{ github.event.repository.name }}-container-${{ inputs.DEPLOY_ENV }}
        location: 'West Europe'