name: Prepare pipeline and set variables

on:
  workflow_call:
    inputs:
      rust:
        description: Rust project features
        default: false
        type: boolean

      node:
        description: Node project features
        default: false
        type: boolean

    outputs:
      deploy_platform:
        description: Deployment platform (e.g. azure, flyio...)
        value: ${{ jobs.prepare-pipeline-vars.outputs.deploy_platform }}

      deploy_env:
        description: Deployment environment (prod, stag or dev)
        value: ${{ jobs.prepare-pipeline-vars.outputs.deploy_env }}

      image_name:
        description: Name of the container image
        value: ${{ jobs.prepare-pipeline-vars.outputs.image_name }}

      rust_package_version:
        description: Package version of the rust crate
        value: ${{ jobs.prepare-pipeline-vars.outputs.rust_package_version }}
      
      node_package_version:
        description: Package version of the node project
        value: ${{ jobs.prepare-pipeline-vars.outputs.node_package_version }}

jobs:
  prepare-pipeline-vars:
    runs-on: ubuntu-latest

    outputs:
      deploy_platform: ${{ steps.deploy-platform.outputs.DEPLOY_PLATFORM }}
      deploy_env: ${{ steps.deploy-env.outputs.DEPLOY_ENV }}
      image_name: ${{ steps.image-name.outputs.IMAGE_NAME }}
      rust_package_version: ${{ steps.rust-package-version.outputs.PACKAGE_VERSION }}
      node_package_version: ${{ steps.node-package-version.outputs.PACKAGE_VERSION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get deployment platform
        id: deploy-platform
        env:
          DEPLOY_PLATFORM: ${{ vars.DEPLOY_PLATFORM }}
        run: |
          if [[ -z $DEPLOY_PLATFORM ]]; then
            DEPLOY_PLATFORM="None"
          fi

          echo "DEPLOY_PLATFORM=$DEPLOY_PLATFORM"
          echo "DEPLOY_PLATFORM=$DEPLOY_PLATFORM" >> $GITHUB_OUTPUT

      - name: Get project type
        id: deploy-env
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          echo "Checking deployment environment"

          if [[ $BRANCH == "main" || $BRANCH == "master" ]]; then
            DEPLOY_ENV="prod"
          elif [[ $BRANCH == "staging" ]]; then
            DEPLOY_ENV="stag"
          else
            DEPLOY_ENV="dev"
          fi

          echo "DEPLOY_ENV=$DEPLOY_ENV"
          echo "DEPLOY_ENV=$DEPLOY_ENV" >> $GITHUB_OUTPUT

      - name: Get image name
        id: image-name
        run: |
          IMAGE_NAME=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')

          echo "IMAGE_NAME=$IMAGE_NAME"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Get Rust package version
        if: ${{ inputs.rust == true }}
        id: rust-package-version
        env:
          DEPLOY_ENV: ${{ steps.deploy-env.outputs.DEPLOY_ENV }}
        run: |
          echo "Checking package version..."

          if [[ $DEPLOY_ENV != "prod" ]]; then
            VERSION_SUFFIX="-$DEPLOY_ENV+$(git rev-parse --short HEAD)"
          fi

          PACKAGE_VERSION="$(cat package.json | jq -r '.version')$VERSION_SUFFIX"
          PACKAGE_VERSION=$(echo $PACKAGE_VERSION) | tr -d ''

          echo "PACKAGE_VERSION=$PACKAGE_VERSION"
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_OUTPUT
        
      - name: Get Node package version
        if: ${{ inputs.node == true }}
        id: node-package-version
        env:
          DEPLOY_ENV: ${{ steps.deploy-env.outputs.DEPLOY_ENV }}
        run: |
          echo "Checking package version..."

          if [[ $DEPLOY_ENV != "prod" ]]; then
            VERSION_SUFFIX="-$DEPLOY_ENV+$(git rev-parse --short HEAD)"
          fi

          PACKAGE_VERSION="$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[0].version')$VERSION_SUFFIX"
          PACKAGE_VERSION=$(echo $PACKAGE_VERSION) | tr -d ''

          echo "PACKAGE_VERSION=$PACKAGE_VERSION"
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_OUTPUT

      - name: Write pipeline vars summary
        run: |
          export SUMMARY="### Prepare pipeline:
          <table>
            <tr>
              <td>🚀 Deployment platform</td>
              <td>${{ steps.deploy-platform.outputs.DEPLOY_PLATFORM }}</td>
            </tr>
            <tr>
              <td>🎯 Deployment environment</td>
              <td>${{ steps.deploy-env.outputs.DEPLOY_ENV }}</td>
            </tr>
            <tr>
              <td>🐳 Image name</td>
              <td>${{ steps.image-name.outputs.IMAGE_NAME }}</td>
            </tr>"

            if [[ "${{ inputs.rust }}" == "true" ]]; then
              SUMMARY+="
              <tr>
                <td>📦 Rust package version</td>
                <td>${{ steps.rust-package-version.outputs.PACKAGE_VERSION }}</td>
              </tr>"
            fi

            if [[ "${{ inputs.node }}" == "true" ]]; then
              SUMMARY+="
              <tr>
                <td>📦 Rust package version</td>
                <td>${{ steps.node-package-version.outputs.PACKAGE_VERSION }}</td>
              </tr>"
            fi

          SUMMARY+=""
          </table>"
          
          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY

  prepare-env-vars:
    needs: prepare-pipeline-vars
    if: |
      needs.prepare-pipeline-vars.outputs.DEPLOY_ENV == 'prod' ||
      needs.prepare-pipeline-vars.outputs.DEPLOY_ENV == 'stag'

    runs-on: ubuntu-latest

    steps:
      - name: Validate required variables
        id: required-vars
        env:
          DEPLOY_PLATFORM: ${{ needs.prepare-pipeline-vars.outputs.deploy_platform }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
          VARS_CONTEXT: ${{ toJson(vars) }}
        run: |
          if [[ $DEPLOY_PLATFORM == 'azure' ]]; then
            required_variables+=(AZURE_CLIENT_ID AZURE_SUBSCRIPTION_ID AZURE_TENANT_ID)
          fi

          while IFS= read -r key; do
            export "$key=PRESENT"
          done < <(echo "$SECRETS_CONTEXT" | jq -r 'keys[]')

          while IFS= read -r key; do
            export "$key=PRESENT"
          done < <(echo "$VARS_CONTEXT" | jq -r 'keys[]')

          missing_variables=()

          for var in "${required_variables[@]}"; do
            if [[ -z ${!var} ]]; then
              missing_variables+=($var)
            else
              echo "Variable \"$var\" is present"
            fi
          done

          if [[ ${#missing_variables[@]} -gt 0 ]]; then
            for var in "${missing_variables[@]}"; do
              echo "Missing \"$var\" variable"
            done
            exit 1
          fi
