name: Project pipeline to deploy rust projects using containers

on:
  workflow_call:

jobs:
  prepare-pipeline:
    uses: ./.github/workflows/prepare-pipeline.yml
    secrets: inherit

  lint-and-test:
    uses: ./.github/workflows/rust/lint-and-test.yml
    needs: [prepare-pipeline]
    secrets: inherit
    with:
      DEPLOY_ENV: ${{ needs.prepare-pipeline.outputs.DEPLOY_ENV }}

  build-and-push-image:
    uses: ./.github/workflows/container/build-and-push.yml
    needs: [prepare-pipeline, lint-and-test]
    secrets: inherit
    with:
      DEPLOY_ENV: ${{ needs.prepare-pipeline.outputs.DEPLOY_ENV }}
      IMAGE_NAME: ${{ needs.prepare-pipeline.outputs.IMAGE_NAME }}

  deploy-aci:
    uses: ./.github/workflows/container/deploy-aci.yml
    needs: [prepare-pipeline, build-and-push-image, terraform-apply]
    secrets: inherit
    with:
      DEPLOY_ENV: ${{ needs.prepare-pipeline.outputs.DEPLOY_ENV }}
      IMAGE_NAME: ${{ needs.prepare-pipeline.outputs.IMAGE_NAME }}

  terraform-plan:
    uses: ./.github/workflows/terraform/plan.yml
    needs: [prepare-pipeline, build-and-push-image]
    secrets: inherit
    with:
      DEPLOY_ENV: ${{ needs.prepare-pipeline.outputs.DEPLOY_ENV }}

  terraform-apply:
    uses: ./.github/workflows/terraform/apply.yml
    needs: [prepare-pipeline, terraform-plan]
    secrets: inherit
    with:
      DEPLOY_ENV: ${{ needs.prepare-pipeline.outputs.DEPLOY_ENV }}
