name: Project pipeline to deploy rust projects using containers

on:
  workflow_call:

jobs:
  prepare-pipeline:
    uses: ./.github/workflows/prepare-pipeline.yml
    secrets: inherit

  terraform:
    uses: ./.github/workflows/terraform.yml
    needs: [prepare-pipeline, build-and-push-image]
    secrets: inherit
    with:
      DEPLOY_ENV: ${{ needs.prepare-pipeline.outputs.DEPLOY_ENV }}

  rust-lint:
    uses: ./.github/workflows/rust-lint-and-test.yml
    needs: [prepare-pipeline]
    secrets: inherit
    with:
      DEPLOY_ENV: ${{ needs.prepare-pipeline.outputs.DEPLOY_ENV }}

  build-and-push-image:
    uses: ./.github/workflows/docker-build-and-push.yml
    needs: [prepare-pipeline, rust-lint]
    secrets: inherit
    with:
      DEPLOY_ENV: ${{ needs.prepare-pipeline.outputs.DEPLOY_ENV }}
      IMAGE_NAME: ${{ needs.prepare-pipeline.outputs.IMAGE_NAME }}

  deploy-azure:
    uses: ./.github/workflows/deploy-azure.yml
    if: ${{ needs.prepare-pipeline.outputs.DEPLOY_PLATFORM == 'azure' }}
    needs: [prepare-pipeline, build-and-push-image]
    secrets: inherit
    with:
      PROJECT_TYPE: ${{ needs.prepare-pipeline.outputs.PROJECT_TYPE }}
      DEPLOY_ENV: ${{ needs.prepare-pipeline.outputs.DEPLOY_ENV }}
      IMAGE_PATH: ${{ needs.build-and-push-image.outputs.DOCKER_IMAGE }}
