name: Apply terraform plan

on:
  workflow_call:
    inputs:
      DEPLOY_ENV:
        description: The environment to deploy to
        required: true
        type: string

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    
    environment: ${{ inputs.DEPLOY_ENV }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.2

      - name: Log in to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform apply
        run: terraform apply -auto-approve -var "deploy_env=${{ github.event.inputs.DEPLOY_ENV }}"
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
