name: Terraform pipeline to deploy infrastructure using terraform

on:
  workflow_call:

jobs:
  prepare-pipeline:
    uses: ./.github/workflows/prepare-pipeline.yml
    secrets: inherit

  terraform:
    uses: ./.github/workflows/terraform.yml
    needs: [prepare-pipeline]
    secrets: inherit
    with:
      DEPLOY_ENV: ${{ needs.prepare-pipeline.outputs.DEPLOY_ENV }}
