name: Apply terraform plan

on:
  workflow_call:
    inputs:
      DEPLOY_ENV:
        description: The environment to deploy to
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    
    environment: ${{ inputs.DEPLOY_ENV }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.2
      
      - name: Terraform plan
        run: terraform plan -var "deploy_env=${{ github.event.inputs.DEPLOY_ENV }}"
        working-directory: terraform
        env:
          ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}

      - name: Save terraform plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform.plan

  terraform-apply:
    runs-on: ubuntu-latest

    needs: [terraform-plan]
    
    environment: ${{ inputs.DEPLOY_ENV }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.2

      - name: Log in to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform apply
        run: terraform apply -auto-approve -var "deploy_env=${{ github.event.inputs.DEPLOY_ENV }}"
        working-directory: terraform
        env:
          ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
