name: Validate the package version

on:
  workflow_call:
    inputs:
      deploy_env:
        description: Deployment environment (prod, stag or dev)
        required: true
        type: string

      package_version:
        description: The version of the package.
        required: true
        type: string

jobs:
  validate-version:
    if: inputs.deploy_env == 'prod' || inputs.deploy_env == 'stag'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate SemVer version against Regex
        env:
          PACKAGE_VERSION: ${{ inputs.package_version }}
        run: |
          echo "Validating package version $PACKAGE_VERSION"

          SEMVER_REGEX='^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'

          if echo "$PACKAGE_VERSION" | grep -Eq "$SEMVER_REGEX"; then
            echo "SemVer regex matched version $PACKAGE_VERSION"
            exit 0
          else
            echo "SemVer regex did not match version $PACKAGE_VERSION"
            exit 1
          fi

      - name: Check if release exsists
        if: inputs.deploy_env == 'prod'
        env:
          PACKAGE_VERSION: ${{ inputs.package_version }}
        run: |
          if git rev-parse "refs/tags/$PACKAGE_VERSION" >/dev/null 2>&1; then
              echo "Tag $PACKAGE_VERSION already exists."
              exit 1
          else
              echo "Tag $PACKAGE_VERSION does not exists."
              exit 0
          fi
